server/Naot Lemida Manage V2/Models/City.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Naot_Lemida_Manage_V2.Models
{
    public class City
    {
        public int ID { get; set; }
        [Required(ErrorMessage ="בבקשה הזן שם של העיר.")]
        [Display(Name = "עיר")]
        public String Name { get; set; }
        public virtual ICollection<School> Schools { get; set; }
    }
}

server/Naot Lemida Manage V2/Controllers/CitiesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Naot_Lemida_Manage_V2.Models;

namespace Naot_Lemida_Manage_V2.Controllers
{
    public class CitiesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Cities
        public ActionResult Index()
        {
            return View(db.Cities.ToList());
        }

        // GET: Cities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return PartialView(city);
        }

        // GET: Cities/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: Cities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Cities.Add(city);
                db.SaveChanges();
                return PartialView("Success");
            }

            return PartialView(city);
        }

        // GET: Cities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return PartialView(city);
        }

        // POST: Cities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Entry(city).State = EntityState.Modified;
                db.SaveChanges();
                return PartialView("Success");
            }
            return PartialView(city);
        }

        // GET: Cities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return PartialView(city);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed([Bind(Include = "ID")] City city)
        {
            city = db.Cities.Find(city.ID);
            db.Cities.Remove(city);
            db.SaveChanges();
            return PartialView("Success");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

server/Naot Lemida Manage V2/Views/Cities/Create.cshtml
@model Naot_Lemida_Manage_V2.Models.City

@{
    ViewBag.Title = "יצירת עיר חדשה";
}

<h2>יצירת עיר חדשה</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>עיר</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}

server/Naot Lemida Manage V2/Views/Cities/Delete.cshtml
@model Naot_Lemida_Manage_V2.Models.City

@{
    ViewBag.Title = "מחיקת עיר";
}

<h2>מחיקת עיר</h2>

<h3>האם את/ה בטוח/ה שברצונך למחוק עיר זו?</h3>
<div>
    <h4>עיר</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.ID)

    }
</div>

server/Naot Lemida Manage V2/Views/Cities/Details.cshtml
@model Naot_Lemida_Manage_V2.Models.City

@{
    ViewBag.Title = "פרטי העיר";
}

<h2>פרטי העיר</h2>

<div>
    <h4>עיר</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>

server/Naot Lemida Manage V2/Views/Cities/Edit.cshtml
@model Naot_Lemida_Manage_V2.Models.City

@{
    ViewBag.Title = "עריכת פרטי העיר";
}

<h2>עריכת פרטי העיר</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>עיר</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

server/Naot Lemida Manage V2/Views/Cities/Index.cshtml
@model IEnumerable<Naot_Lemida_Manage_V2.Models.City>

@{
    ViewBag.Title = "רשימת ערים";
}

<h2>רשימת ערים</h2>

<link href='@Url.Content("~/Content/themes/base/all.css")' rel="stylesheet" type="text/css" />

<p>
    @Html.ActionLink("ליצור עיר חדשה", "Create","Cities", new { }, new { @class = "viewDialogCreate", data_dialog_title = "יצירת עיר חדשה " })
</p>

@section Scripts {
    <script>
        $(document).ready(function () {

            $.ajaxSetup({ cache: false });
            $(".viewDialogCreate").on("click", function (e) {

                e.preventDefault();
                $("<div id='dialogContent'></div>")
                    .addClass("dialog")
                    .appendTo("body")
                    .dialog({
                        title: $(this).attr("data-dialog-title"),
                        modal: true,
                        width: 350,
                        height: 500,

                        buttons: {
                            "צור": function () {
                                $.ajax({
                                    url: "@Url.Action("Create")",
                                    type: "POST",
                                    data: $('form').serialize(),
                                    datatype: "json",
                                    success: function (result) {
                                        $("#dialogContent").html(result);
                                    }
                                });
                            }
                        },

                        show:
                        {
                            effect: 'clip',
                            duration: 450
                        },
                        hide: {
                            effect: 'clip',
                            duration: 450
                        },
                        showOpt: { direction: 'up' },
                        close: function (event, ui) { $(this).dialog('destroy').remove(); },

                    })
                    .load(this.href);
            });

             $(".viewDialogDelete").on("click", function (e) {

                e.preventDefault();
                $("<div id='dialogContent'></div>")
                    .addClass("dialog")
                    .appendTo("body")
                    .dialog({
                        title: $(this).attr("data-dialog-title"),
                        modal: true,
                        width: 350,
                        height: 500,
                        buttons: {
                            "מחק": function () {
                                $.ajax({
                                    url: "@Url.Action("Delete")",
                                    type: "POST",
                                    data: $('form').serialize(),
                                    datatype: "json",
                                    success: function (result) {

                                        $("#dialogContent").html(result);
                                    }
                                });
                            }
                        },

                        show:
                    {
                        effect: 'clip',
                        duration: 450
                    },
                        hide: {
                            effect: 'clip',
                            duration: 450
                        },
                        showOpt: { direction: 'up' },
                        close: function (event, ui) { $(this).dialog('destroy').remove(); }
                    })
                    .load(this.href);
            });
            $(".viewDialogEdit").on("click", function (e) {

                e.preventDefault();
                $("<div id='dialogContent'></div>")
                    .addClass("dialog")
                    .appendTo("body")
                    .dialog({
                        title: $(this).attr("data-dialog-title"),
                        modal: true,
                        width: 350 ,
                        height: 500 ,
                        buttons: {
                            "שמור": function () {
                                $.ajax({
                                    url: "@Url.Action("Edit")",
                                    type: "POST",
                                    data: $('form').serialize(),
                                    datatype: "json",
                                    success: function (result) {

                                        $("#dialogContent").html(result);
                                    }
                                });
                            }
                        },

                        show:
                    {
                        effect: 'clip',
                        duration: 450
                    },
                        hide: {
                            effect: 'clip',
                            duration: 450
                        },
                        showOpt: { direction: 'up' },
                        close: function (event, ui) {
                            $(this).dialog('destroy').remove();
                        }
                    })
                    .load(this.href);
            });
            $(".close").on("click", function (e) {
                e.preventDefault();
                $(this).closest(".dialog").dialog("close");
            });
        })
</script>
<script src='@Url.Content("~/Scripts/jquery-1.10.2.min.js")' type="text/javascript"></script>
<script src='@Url.Content("~/Scripts/jquery-ui-1.11.4.min.js")' type="text/javascript"></script>
    }

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
       
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>

            @Html.ActionLink("ערוך", "Edit", "Cities", new { id = item.ID }, new { @class = "viewDialogEdit", data_dialog_title = "עריכת פרטי העיר" }) |
            @Html.ActionLink("מחק", "Delete", "Cities", new { id = item.ID }, new { @class = "viewDialogDelete", data_dialog_title = "מחיקת עיר" })
        </td>
    </tr>
}

</table>

server/Naot Lemida Manage V2/Views/Cities/Success.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <h2>הפעולה הושלמה בהצלחה.</h2>
    <script>
    $(document).ready(function () {
        setTimeout(function() {
            window.location.href = "@Url.Action("Index", "Cities")";
        }, 2000);
    })
    </script>

</body>
</html>