server/Naot Lemida Manage V2/Models/School.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Naot_Lemida_Manage_V2.Models
{
    public class School
    {
        public int ID { get; set; }
        [Display(Name = "שם המוסד")]
        public String Name { get; set; }
        [Display(Name = "רחוב")]
        public String Street { get; set; }
        [Display(Name = "מספר")]
        public int Number { get; set; }
        [Display(Name = "עיר")]
        public int CityID { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<ApplicationUser> ApplicationUsers { get; set; }
    }
}

server/Naot Lemida Manage V2/Controllers/SchoolsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Naot_Lemida_Manage_V2.Models;

namespace Naot_Lemida_Manage_V2.Controllers
{
    public class SchoolsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Schools
        public ActionResult Index()
        {
            var schools = db.Schools.Include(s => s.City);
            return View(schools.ToList());
        }

        // GET: Schools/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            School school = db.Schools.Find(id);
            if (school == null)
            {
                return HttpNotFound();
            }
            return PartialView(school);
        }

        // GET: Schools/Create
        public ActionResult Create()
        {
            ViewBag.CityID = new SelectList(db.Cities, "ID", "Name");
            return PartialView();
        }

        // POST: Schools/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Street,Number,CityID")] School school)
        {
            if (ModelState.IsValid)
            {
                db.Schools.Add(school);
                db.SaveChanges();
                return PartialView("Success");
            }

            ViewBag.CityID = new SelectList(db.Cities, "ID", "Name", school.CityID);
            return View(school);
        }

        // GET: Schools/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            School school = db.Schools.Find(id);
            if (school == null)
            {
                return HttpNotFound();
            }
            ViewBag.CityID = new SelectList(db.Cities, "ID", "Name", school.CityID);
            return PartialView(school);
        }

        // POST: Schools/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Street,Number,CityID")] School school)
        {
            if (ModelState.IsValid)
            {
                db.Entry(school).State = EntityState.Modified;
                db.SaveChanges();
                return PartialView("Success");
            }
            ViewBag.CityID = new SelectList(db.Cities, "ID", "Name", school.CityID);
            return View(school);
        }

        // GET: Schools/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            School school = db.Schools.Find(id);
            if (school == null)
            {
                return HttpNotFound();
            }
            return PartialView(school);
        }

        // POST: Schools/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed([Bind(Include = "ID")] School school)
        {
             school = db.Schools.Find(school.ID);
            db.Schools.Remove(school);
            db.SaveChanges();
            return PartialView("Success");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

server/Naot Lemida Manage V2/Views/Schools/Create.cshtml
@model Naot_Lemida_Manage_V2.Models.School

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>School</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityID, "עיר", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CityID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CityID, "", new { @class = "text-danger" })
            </div>
        </div>

        
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

server/Naot Lemida Manage V2/Views/Schools/Delete.cshtml
@model Naot_Lemida_Manage_V2.Models.School

@{
    ViewBag.Title = "מחיקת מוסד";
}

<h2>מחיקת מוסד</h2>

<h3>האם את/ה בטוח/ה שברצונך למחוק מוסד זה</h3>
<div>
    <h4>מוסד</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

    </dl>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.ID)

    }
</div>

server/Naot Lemida Manage V2/Views/Schools/Details.cshtml
@model Naot_Lemida_Manage_V2.Models.School

@{
    ViewBag.Title = "פרטי המוסד";
}

<h2>פרטי המוסד</h2>

<div>
    <h4>מוסד</h4>
    <hr />
    <dl class="dl-horizontal">
        

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

    </dl>
</div>

server/Naot Lemida Manage V2/Views/Schools/Edit.cshtml
@model Naot_Lemida_Manage_V2.Models.School

@{
    ViewBag.Title = "עריכת פרטי המוסד";
}

<h2>עריכת פרטי המוסד</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>מוסד</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityID, "עיר", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CityID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CityID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

server/Naot Lemida Manage V2/Views/Schools/Index.cshtml
@model IEnumerable<Naot_Lemida_Manage_V2.Models.School>

@{
    ViewBag.Title = "רשימת מוסדות חינוך";
}

<h2>רשימת מוסדות חינוך</h2>

<link href='@Url.Content("~/Content/themes/base/all.css")' rel="stylesheet" type="text/css" />
<p>
    @Html.ActionLink("ליצור מוסד חדש", "Create", "Schools", new { }, new { @class = "viewDialogCreate", data_dialog_title = "יצירת מוסד חדש " })
</p>

@section Scripts {
    <script>
        $(document).ready(function () {

            $.ajaxSetup({ cache: false });
            $(".viewDialogCreate").on("click", function (e) {

                e.preventDefault();
                $("<div id='dialogContent'></div>")
                    .addClass("dialog")
                    .appendTo("body")
                    .dialog({
                        title: $(this).attr("data-dialog-title"),
                        modal: true,
                        width: 350,
                        height: 500,

                        buttons: {
                            "צור": function () {
                                $.ajax({
                                    url: "@Url.Action("Create")",
                                    type: "POST",
                                    data: $('form').serialize(),
                                    datatype: "json",
                                    success: function (result) {
                                        $("#dialogContent").html(result);
                                    }
                                });
                            }
                        },

                        show:
                        {
                            effect: 'clip',
                            duration: 450
                        },
                        hide: {
                            effect: 'clip',
                            duration: 450
                        },
                        showOpt: { direction: 'up' },
                        close: function (event, ui) { $(this).dialog('destroy').remove(); },

                    })
                    .load(this.href);
            });

             $(".viewDialogDelete").on("click", function (e) {

                e.preventDefault();
                $("<div id='dialogContent'></div>")
                    .addClass("dialog")
                    .appendTo("body")
                    .dialog({
                        title: $(this).attr("data-dialog-title"),
                        modal: true,
                        width: 350,
                        height: 500,
                        buttons: {
                            "מחק": function () {
                                $.ajax({
                                    url: "@Url.Action("Delete")",
                                    type: "POST",
                                    data: $('form').serialize(),
                                    datatype: "json",
                                    success: function (result) {

                                        $("#dialogContent").html(result);
                                    }
                                });
                            }
                        },

                        show:
                    {
                        effect: 'clip',
                        duration: 450
                    },
                        hide: {
                            effect: 'clip',
                            duration: 450
                        },
                        showOpt: { direction: 'up' },
                        close: function (event, ui) { $(this).dialog('destroy').remove(); }
                    })
                    .load(this.href);
            });
            $(".viewDialogEdit").on("click", function (e) {

                e.preventDefault();
                $("<div id='dialogContent'></div>")
                    .addClass("dialog")
                    .appendTo("body")
                    .dialog({
                        title: $(this).attr("data-dialog-title"),
                        modal: true,
                        width: 350 ,
                        height: 500 ,
                        buttons: {
                            "שמור": function () {
                                $.ajax({
                                    url: "@Url.Action("Edit")",
                                    type: "POST",
                                    data: $('form').serialize(),
                                    datatype: "json",
                                    success: function (result) {

                                        $("#dialogContent").html(result);
                                    }
                                });
                            }
                        },

                        show:
                    {
                        effect: 'clip',
                        duration: 450
                    },
                        hide: {
                            effect: 'clip',
                            duration: 450
                        },
                        showOpt: { direction: 'up' },
                        close: function (event, ui) {
                            $(this).dialog('destroy').remove();
                        }
                    })
                    .load(this.href);
            });
            $(".close").on("click", function (e) {
                e.preventDefault();
                $(this).closest(".dialog").dialog("close");
            });
        })
    </script>
    <script src='@Url.Content("~/Scripts/jquery-1.10.2.min.js")' type="text/javascript"></script>
    <script src='@Url.Content("~/Scripts/jquery-ui-1.11.4.min.js")' type="text/javascript"></script>
}




<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Street)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Number)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Street)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Number)
        </td>
        <td>
             @Html.ActionLink("ערוך", "Edit", "Schools", new { id = item.ID }, new { @class = "viewDialogEdit", data_dialog_title = "עריכת פרטי המוסד" }) |
            @Html.ActionLink("מחק", "Delete", "Schools", new { id = item.ID }, new { @class = "viewDialogDelete", data_dialog_title = "מחיקת מוסד" })
        </td>
    </tr>
}

</table>

server/Naot Lemida Manage V2/Views/Schools/Success.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <h2>הפעולה הושלמה בהצלחה.</h2>
    <script>
    $(document).ready(function () {
        setTimeout(function() {
            window.location.href = "@Url.Action("Index", "Schools")";
        }, 1000);
    })
    </script>

</body>
</html>